M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-07-01T08:41:17-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-01T08:41:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X74.0Y-39.4
X74.0Y-135.6
X207.0Y-39.4
X207.0Y-135.6
M30
